spring:
   datasource:
      username: user1
      url: jdbc:mysql://3.17.36.95:3306/hr
      password: pass123
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
      hibernate:
         ddl-auto: update
   application:
      name: flight-booking-system
eureka:
   client:
      service-url:
         defaultZone: http://localhost:8761/eureka
      fetch-registry: false
      register-with-eureka: true
server:
   port: '8082'
logging:
   file:
      name: flight-booking-system.log